### ISSUE TITLE
Setup pipeline

### ISSUE THREAD

**Issue by flaxel** [whzinformatik/stocktrader#6]
Create a GitHub Pipeline with different actions:

- [x] spotless
- [x] build project
- [x] test project
- [ ] sonarcloud
- [x] codeql

**Comment by flaxel** [comment]
@fgr So far it has worked very well to set up the pipeline. I was about to start working on Sonarcloud. For that I need the confirmation of the organization. You should have received an email. If so, can you confirm this?

**Comment by fgr** [comment]
Thanks @flaxel for setting up the pipeline. I just set up the sonarcloud account.

**Comment by flaxel** [comment]
@fgr If I want to analyze a new project I get the error message `Insufficient privileges`. Should there be a project for the stocktrader or can I get the permissions to create a project?

**Comment by fgr** [comment]
@flaxel I just gave you all possible permissions for the project on SonarCloud...
